### ISSUE TITLE
Update vmhgfs-fix for newest docker-tools installable

### ISSUE THREAD

**Issue by gegere** [frapposelli/boot2docker#2]
Create `boot2docker.iso` vmhgfs-fix for `v1.8.3`

Running the newest docker-tools setup will give you the following version at this time:
`
docker-machine version 0.4.1
`

$  **docker version**
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Get http:///var/run/docker.sock/v1.19/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

Resulting in: 
$ **Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)**

**Comment by gegere** [comment]
More information on the newer version relating to this problem: https://github.com/docker/machine/issues/641

Please continue the great work you have!

**Comment by frapposelli** [comment]
This branch is outdated, everything has been merged upstream into boot2docker, you should use that.

**Comment by gegere** [comment]
I understand this branch is outdate, I am having the same issue as https://github.com/docker/machine/issues/641#issuecomment-148955087

Simply noting... if I understand correctly. Thanks!
